server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: oauth2-server
  freemarker:
    suffix: .ftl
    cache: false
    encoding: UTF-8
    template-loader-path: classpath:/templates

mybatis:
  mapper-locations: classpath:/mapper/**
