server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: oauth2-resource

eureka:
  host: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8182}/eureka/
