server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: oauth2-server
  freemarker:
    suffix: .ftl
    cache: false
    encoding: UTF-8
    template-loader-path: classpath:/templates

eureka:
  host: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${server.port:8182}/eureka/

mybatis:
  mapper-locations: classpath:/mapper/**
